### ISSUE TITLE
 The game does not see the cards

### ISSUE THREAD

**Issue by Brawn000** [benerkaya/Deity-Zenith-Warcraft-3-reforged#1]
здравствуйте, у меня не видит игра ваши карты в.1.32.10 
Hello, I can't see your cards in the game.1.32.10

**Comment by Brawn000** [comment]
a pirated version of the game, maps are displayed on the license, maybe it's the version of the game?

**Comment by benerkaya** [comment]
Do you mean maps by "cards" ? Does your game dont show maps? Theres no
problem in game currently but if you try on a pirate version then i dont
know what causes them to not work

9 Kas 2022 Çar 07:05 tarihinde Brawn000 ***@***.***> şunu
yazdı:
